[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mantle_sepolia = "${MANTLE_SEPOLIA_RPC_URL}"

[etherscan]
mantle_sepolia = { key = "${MANTLESCAN_API_KEY}", url = "https://api-sepolia.mantlescan.xyz/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
